// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMVCApplication.Data;

#nullable disable

namespace MyMVCApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210053238_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyMVCApplication.Models.Account", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("MyMVCApplication.Models.Enrollment", b =>
                {
                    b.Property<string>("EnrollmentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SSFCLASSSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFDAYS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFEDPCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SSFENDTIME")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SSFMAXSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFROOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSCHOOLYEAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSECTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SSFSTARTTIME")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SSFSTATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSUBJCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFXM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("SFSUBJCODE");

                    b.HasIndex("SSFEDPCODE");

                    b.HasIndex("STFSTUDID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("MyMVCApplication.Models.Student", b =>
                {
                    b.Property<string>("STFSTUDID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("STFSTUDCOURSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDFNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDLNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDMNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDREMARKS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STFSTUDSTATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STFSTUDYEAR")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("STFSTUDID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("MyMVCApplication.Models.Subject", b =>
                {
                    b.Property<string>("SFSUBJCODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SFSUBJCATEGORY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJCODEREQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJCOURSECODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJCURRICULUMCOURSECODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJDESC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJECTSTATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJREGOFRNG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SFSUBJREQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SFSUBJUNITS")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("SFSUBJCODE");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("MyMVCApplication.Models.SubjectSchedule", b =>
                {
                    b.Property<string>("SSFEDPCODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SSFCLASSSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFDAYS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SSFENDTIME")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SSFMAXSIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFROOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSCHOOLYEAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSECTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SSFSTARTTIME")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SSFSTATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFSUBJCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSFXM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSFEDPCODE");

                    b.ToTable("SubjectSchedule");
                });

            modelBuilder.Entity("MyMVCApplication.Models.Enrollment", b =>
                {
                    b.HasOne("MyMVCApplication.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SFSUBJCODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMVCApplication.Models.SubjectSchedule", "SubjectSchedule")
                        .WithMany()
                        .HasForeignKey("SSFEDPCODE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMVCApplication.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("STFSTUDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("SubjectSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
